### ISSUE TITLE
process exited by signal SIGSEGV

### ISSUE THREAD

**Issue by rgadda** [nearform/node-clinic-bubbleprof-examples#5]
Getting below error while running example for server-side-rendering

```
➜  server-side-rendering git:(master) ✗ clinic bubbleprof -- node src/server
internal/modules/cjs/loader.js:596
    throw err;
    ^

Error: Cannot find module '/Users/rajiv.gadda/Documents/Workspace/personal/clinicjs/node-clinic-bubbleprof-examples/server-side-rendering/src/server'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at getMainDirectory (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/collect/system-info.js:19:14)
    at systemInfo (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/collect/system-info.js:33:20)
    at Object.<anonymous> (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/injects/logger.js:15:55)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Module.require (internal/modules/cjs/loader.js:650:17)
/usr/local/lib/node_modules/clinic/bin.js:237
      if (err) throw err
               ^

Error: process exited by signal SIGSEGV
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/clinic/node_modules/@nearform/bubbleprof/index.js:80:13)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
```

**Comment by kamil-mech** [comment]
Thank you for flagging this. You have helped uncovering:
- Issue in documentation, (fix https://github.com/nearform/node-clinic-bubbleprof-examples/pull/8 )
- Issue in node core https://github.com/nodejs/node/issues/22042

Please run ` clinic bubbleprof -- node server` and then `node stories.js`.
You may need to `npm i` first in that directory

**Comment by rgadda** [comment]
@kamil-mech the above-updated commands work. thank you for your prompt response. Always happy to help 😄
